modified query index for compatibility with pandas
MarvinT/calmap pull request #9
Opened 2020-08-10 16:56 UTC by zztin

In this fix 2 issues are addressed:

1. Tests failing on current version (216fc6be, tag: v0.0.8): `../calmap/__init__.py:238 KeyError`
Details please see pytest log: https://pastebin.ubuntu.com/p/TQt7WRFzpc/

2. Future warning
current_projects/calmap/calmap/__init__.py:181: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series.  To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
    "week": by_day.index.week,

My running environment:
- Python 3.8.3
- Pandas 1.1.0

Discussions and comments are very welcome!

2021-01-07 11:58 UTC, zztin commented
Imcompatible with python 2.7 and 3.5, passed with python 3.6+ due to pandas version bump to v1.0. Would you consider merging the pull request?

2021-01-31 16:20 UTC, ErikBjare commented
These changes look great, having similar issues with recent pandas. I hope dropping Python 2.7 support isn't an issue (shouldn't be anyway).

@MarvinT Any chance they'll be merged?

2021-01-31 16:21 UTC, ErikBjare commented on calmap/__init__.py
> +    cb1.set_label('CTimer clocks')
This label looks a bit weird, is it correct?

2021-02-14 06:48 UTC, MarvinT requested changes
Hey @zztin , sorry I didn't get to this earlier.

Thanks for updating the package. I am comfortable removing support for 2.7 and 3.5
Any idea why 3.7 tests are failing?
We'll have to change .travis.yml to only push to the compatible py versions because right now I have it push as a universal build.
Can you also format using black?

I've added a few comments inline as well

2021-02-14 06:48 UTC, MarvinT commented on calmap/__init__.py
> +__homepage__ = "https://github.com/zztin/calmap"
I don't mind adding you as a contact but can you leave the homepage pointing to my version since that's what pypi uses.

2021-02-14 06:48 UTC, MarvinT commented on calmap/__init__.py
> -    cmap="Reds",
Is there a reason to change the default behavior here? its a kwarg so if anyone wants reds they can use it but this will change everyone's plots without documenting the changes anywhere...

2021-02-14 06:48 UTC, MarvinT commented on calmap/__init__.py
> +    plt.suptitle(fig_suptitle)
Does this do nothing if fig_suptitle is None?

2021-02-14 06:48 UTC, MarvinT commented on calmap/__init__.py
> +    vmax=16,
I feel like the defaults should be None

2021-02-14 06:48 UTC, MarvinT commented on calmap/__init__.py
> +        color=kwargs.get("fillcolor", "silver"),
what is this change for?

2021-02-14 06:48 UTC, MarvinT commented on calmap/__init__.py
> +        resampling data by day.
Aren't you missing several of the other kwargs you added?

2021-02-14 06:48 UTC, MarvinT commented on calmap/__init__.py
> +                       ticks=range(vmin, vmax + 1))
adding a colorbar should be an optional thing. I personally prefer the clean look of not having a color bar.

2021-03-04 16:37 UTC, lawuka commented
I am also looking for a fix to these two exact issues and I would prefer if the colorbar and other custom changes were left out as @MarvinT is also questioning. Are you still up for making the changes @zztin ?

2021-03-08 12:31 UTC, zztin commented
Hi all!
Yes, I will look into them asap (before next week). Sorry for the delay!

Best,
Liting

On Fri, Mar 5, 2021 at 12:37 AM Alexander Kvist Andreasen <
notifications@github.com> wrote:

> I am also looking for a fix to these two exact issues and I would prefer
> if the colorbar and other custom changes were left out as @MarvinT
> <https://github.com/MarvinT> is also questioning. Are you still up for
> making the changes @zztin <https://github.com/zztin> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/MarvinT/calmap/pull/9#issuecomment-790751998>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH2QX2L4R6ZL32XAIPMZ5GLTB6ZNBANCNFSM4P2E4EAA>
> .
>

2021-03-10 02:06 UTC, fakhavan commented
Hi everyone!
I just wanted to add that I get this error when I was using your library inside one of our notebooks on [Google Colab](https://colab.research.google.com/github/predicthq/phq-data-science-docs/blob/master/unattended-events/part_2_data_exploration.ipynb#scrollTo=pT4ZnjbKrkEM):

<img width="829" alt="Screen Shot 2021-03-10 at 2 16 45 PM" src="https://user-images.githubusercontent.com/56804845/110564134-3d259600-81b1-11eb-967e-62b66c08f35c.png">


This issue goes away when you install pandas 1.0.5 on colab and restart the kernel (runtime).
However wanting to find a better solution, I tried it with [`zztin:master` ](https://github.com/zztin/calmap) with the pre-installed pandas on colab (it's version 1.1.5) and I still got an error at the exact same part with a different error message:

<img width="1366" alt="Screen Shot 2021-03-10 at 2 08 25 PM" src="https://user-images.githubusercontent.com/56804845/110564543-de145100-81b1-11eb-8f43-6347d34c61d6.png">

I'm not sure if this issue is related to colab only or happens on a local environment with the same package versions but I thought it could be useful if you know.
Thank you

2021-03-11 10:25 UTC, zztin commented on calmap/__init__.py
> -    cmap="Reds",
I will revert the change back to its default behavior.

2021-03-11 10:26 UTC, zztin commented on calmap/__init__.py
> +    vmax=16,
I agree.

2021-03-11 13:27 UTC, tai271828 commented
Python 3.7 failure of Travis CI is caused by numpy version,

```
...... (skipped messages)......
Requirement already satisfied: numpy>=1.15 in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from matplotlib>=2.0.0->-r doc/requirements.txt (line 1)) (1.16.4)
...... (skipped messages)......
ERROR: pandas 1.2.3 has requirement numpy>=1.16.5, but you'll have numpy 1.16.4 which is incompatible.
...... (skipped messages)......
ImportError: this version of pandas is incompatible with numpy < 1.16.5
346your numpy version is 1.16.4.
347Please upgrade numpy to >= 1.16.5 to use this pandas version
```

The travis environment shows some specific versions are used. Let me have a look if they raise version dependency issue:

```
# .travis.yml
install:
- pip install -r tests/requirements.txt -r doc/requirements.txt
- pip install -e .
```

and the corresponding requirement file content:

```
# test/requirements.txt
pytest>=4.6
coverage
pytest-cov
python-coveralls

# doc/requirements.txt
pytest>=4.6
coverage
pytest-cov
python-coveralls
matplotlib>=2.0.0
numpydoc
Sphinx<=1.8.2
```

I built from scratch with the above requirement files and follow the pip install part of travis.yml, and I did not get the same error. The dependency issue should be raised by the other steps of travis.

2021-03-11 15:59 UTC, zztin commented
Hi all, 
The pull request has been updated to include the basic changes essential for pandas support and made style changes optional. I also excluded all customized modification that was accidentally committed into the previous PR request. 

Thank you @tai271828 for the Travis CI fix. I've included the changes listed in https://github.com/MarvinT/calmap/pull/10 in this PR. 

I have not taken into account the remark related to Colab notebook. Maybe the author could allow the issue page for submitting other issues?

2021-03-11 16:01 UTC, zztin commented on calmap/__init__.py
> +                       ticks=range(vmin, vmax + 1))
It has been removed from this pull request. I am planning to send another pull request regarding the option to include a heatmap at a later stage.

2021-03-11 16:02 UTC, zztin commented on calmap/__init__.py
> +        resampling data by day.
In the latest version, I think I have included all kw args I added. If there's something missing still let me know!

2021-03-11 16:02 UTC, zztin commented on calmap/__init__.py
> +        color=kwargs.get("fillcolor", "silver"),
It has been removed from the current PR.

2021-03-11 16:04 UTC, zztin commented on calmap/__init__.py
> +    plt.suptitle(fig_suptitle)
I tested it. It still works when fig_suptitle is None. However, I tested with a single year plot, and I didn't test with plotting for multiple years.

2021-03-11 16:05 UTC, zztin commented on calmap/__init__.py
> +__homepage__ = "https://github.com/zztin/calmap"
I have reverted the changes. This was a mistake of mine to include in this PR :)

2021-03-11 16:05 UTC, zztin commented on calmap/__init__.py
> +    cb1.set_label('CTimer clocks')
It's removed in the current PR.

2021-03-11 20:52 UTC, fakhavan commented
I just tested the latest `zztin:master` with Colab and the issues have been fixed. I think the issue was not anything different than an incompatibility between the latest versions of pandas and `calmap` which seems to be fixed with these changes

2021-03-22 06:57 UTC, ErikBjare commented
@MarvinT This looks ready to merge! :tada:

2021-03-23 10:02 UTC, MarvinT reviewed
Alright, thanks for all the work. I think the only thing left is updating the version number and I'll deploy it.

2021-03-23 10:02 UTC, MarvinT commented on calmap/__init__.py
> +        resampling data by day.
alright, looks good

2021-03-23 10:02 UTC, MarvinT commented on calmap/__init__.py
> +    plt.suptitle(fig_suptitle)
great!

2021-03-23 10:02 UTC, MarvinT commented on calmap/__init__.py
>  __version_info__ = ("0", "0", "8")
can you update version info to 0 0 9

2021-03-23 15:23 UTC, ErikBjare commented on calmap/__init__.py
>  __version_info__ = ("0", "0", "8")
```suggestion
__version_info__ = ("0", "0", "9")
```

Here's a one-click apply for you.

2021-03-23 15:24 UTC, ErikBjare commented on calmap/__init__.py
>  __version_info__ = ("0", "0", "8")
```suggestion
__version_info__ = ("0", "0", "9")
```

Here's a one-click apply for you.

2021-03-24 01:24 UTC, MarvinT approved these changes

2021-03-24 01:25 UTC, merged

2021-03-24 01:41 UTC, MarvinT commented
and released! thanks all!